[courses]
    # Fire Preventation
    [courses.1]
        price = 80
        prd_id = "price_1OYhj8D7upUCKzSUwLDe74gH"
        disabled = ""

    # Essentials of Electrical Safety
    [courses.2]
        price = 80
        prd_id = "price_1OYhj8D7upUCKzSUwLDe74gH"
        disabled = ""
    
    # Welding Basics Theory and Safety Precautions 
    [courses.3]
        price = 80
        prd_id = "price_1OYhj8D7upUCKzSUwLDe74gH"
        disabled = ""
    
    # Personal Protective Equipment
    [courses.4]
        price = 80
        # prd_id = "price_1OYiBED7upUCKzSUHzKbBH6Y" test environment
        prd_id = "price_1OYhj8D7upUCKzSUwLDe74gH"
        disabled = ""
    
    # Food Safety and Hygiene
    [courses.5]
        price = 80
        prd_id = "price_1OYhj8D7upUCKzSUwLDe74gH"
        disabled = ""
    
    # Care Course
    [courses.6]
        price = 5
        prd_id = "price_1OVEOWD7upUCKzSU8j7V0QCO" # Testing 5 USD
        disabled = ""
        

[gateways]
    [gateways.stripe]
        key = "REDACTED_STRIPE_LIVE_KEY"
        # key = "REDACTED_STRIPE_TEST_KEY"
    [gateways.paypal]
        # key = "sb"
        key = "REDACTED_PAYPAL_KEY"
        currency = "GBP"

[domain]
    domain = ["https", "healthcarecpd.org"]
